export const ActivityType = {
  ADMIN_LOGIN: "ADMIN_LOGIN",
  MOBILE_LOGIN: "MOBILE_LOGIN",
  MOBILE_LOGOUT: "MOBILE_LOGOUT",
  REFRESH_TOKEN: "REFRESH_TOKEN",

  REGISTER_CUSTOMER: "REGISTER_CUSTOMER",
  REGISTER_TRAINER: "REGISTER_TRAINER",
  VERIFY_EMAIL: "VERIFY_EMAIL",
  RESEND_OTP: "RESEND_OTP",

  UPLOAD_TRAINER_CERTIFICATE: "UPLOAD_TRAINER_CERTIFICATE",

  UPDATE_USER_STATUS: "UPDATE_USER_STATUS",

  VIEW_PROFILE: "VIEW_PROFILE",
} as const;

export const AuditAction = {
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  DELETE: "DELETE",

  APPROVE_TRAINER: "APPROVE_TRAINER",
  REJECT_TRAINER: "REJECT_TRAINER",

  UPDATE_USER_STATUS: "UPDATE_USER_STATUS",
  UPDATE_ROLE_PERMISSIONS: "UPDATE_ROLE_PERMISSIONS",
  UPDATE_GYM_INFO: "UPDATE_GYM_INFO",
  UPDATE_GENERAL_SETTING: "UPDATE_GENERAL_SETTING",

  CREATE_NEWS_CATEGORY: "CREATE_NEWS_CATEGORY",
  UPDATE_NEWS_CATEGORY: "UPDATE_NEWS_CATEGORY",
  DELETE_NEWS_CATEGORY: "DELETE_NEWS_CATEGORY",

  CREATE_NEWS: "CREATE_NEWS",
  UPDATE_NEWS: "UPDATE_NEWS",
  DELETE_NEWS: "DELETE_NEWS",
  PUBLISH_NEWS: "PUBLISH_NEWS",
} as const;

export const ResourceType = {
  USER: "USER",
  ROLE: "ROLE",
  PERMISSION: "PERMISSION",
  ROLE_PERMISSION: "ROLE_PERMISSION",
  CUSTOMER_PROFILE: "CUSTOMER_PROFILE",
  TRAINER_PROFILE: "TRAINER_PROFILE",
  GYM_INFO: "GYM_INFO",
  GENERAL_SETTING: "GENERAL_SETTING",
  REFRESH_TOKEN: "REFRESH_TOKEN",
  VERIFICATION_CODE: "VERIFICATION_CODE",
  NEWS_CATEGORY: "NEWS_CATEGORY",
  NEWS: "NEWS",
} as const;

export const NotificationType = {
  TRAINER_CERTIFICATE_SUBMITTED: "TRAINER_CERTIFICATE_SUBMITTED",
  TRAINER_APPROVED: "TRAINER_APPROVED",
  TRAINER_REJECTED: "TRAINER_REJECTED",

  USER_REGISTERED: "USER_REGISTERED",
  EMAIL_VERIFIED: "EMAIL_VERIFIED",

  SETTING_UPDATED: "SETTING_UPDATED",
  USER_STATUS_UPDATED: "USER_STATUS_UPDATED",
  ROLE_PERMISSION_UPDATED: "ROLE_PERMISSION_UPDATED",
} as const;
